name: flutter_nn
description: Neural network implemented in Dart, interactable in Flutter


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.0-190.0.dev <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  # path_provider: ^2.0.11 # for saving models to Documents

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - lib/models/mnist.json.gz # can also use mnist2.json.gz, though it was trained with less data and epochs
    # - lib/datasets/raw_data/mnist/
    # - lib/datasets/generated_data/mnist/
