name: flutter_neural_network
description: Neural network implemented in Dart, interactable in Flutter


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.0-190.0.dev <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  neural_network:
    path: ../neural_network
  universal_html: ^2.0.8


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - lib/models/mnist2.json
